
const ERR = {
  UNKNOWN: -1,
  UNAUTHORIZED: -2,
  FORBIDDEN: -3,
  UNVERIFIED: -4,
  OBJECT_NOT_FOUND: -5,
  INVALID_ROLE: -6,
  INVALID_FORMAT: -7,
  INVALID_VERSION: -8,
  INVALID_DATA: -9,
  INVALID_USER: -10,

  ACTION_FALSE: -11,
  ALREADY_VERIFIED: -14,

  RENDER_VIEW_REJECTED: -51,
  
  REQUEST_EXPIRED: -103,
  USER_ALREADY_EXIST: -106,
  USER_NOT_EXIST: -107,
  EMAIL_NOT_EXIST: -108,
  INVALID_PASSWORD: -109,
}

Object.freeze(ERR)

export default ERR